create table if not exists public.daily_site_report_audit_log (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.daily_site_reports(id) on delete cascade,
  action text not null,
  reason text,
  changed_by text,
  changed_by_name text,
  changes jsonb not null default '{}'::jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists daily_site_report_audit_idx
  on public.daily_site_report_audit_log (report_id, changed_at desc);

alter table public.daily_site_report_audit_log enable row level security;
drop policy if exists "daily_site_report_audit_select" on public.daily_site_report_audit_log;
create policy "daily_site_report_audit_select" on public.daily_site_report_audit_log
  for select to anon, authenticated using (true);
drop policy if exists "daily_site_report_audit_insert" on public.daily_site_report_audit_log;
create policy "daily_site_report_audit_insert" on public.daily_site_report_audit_log
  for insert to anon, authenticated with check (true);

grant select, insert on public.daily_site_report_audit_log to anon, authenticated;
grant usage, select on sequence public.daily_site_report_audit_log_id_seq to anon, authenticated;
