create table if not exists public.project_billing_records (
  project_id text primary key,
  billing_data jsonb not null default '{}'::jsonb,
  is_closed boolean not null default false,
  closed_at timestamptz,
  closed_by text,
  closed_by_name text,
  updated_at timestamptz not null default now(),
  updated_by text,
  updated_by_name text
);

create table if not exists public.project_billing_audit_log (
  id bigint generated by default as identity primary key,
  project_id text not null,
  action text not null,
  changed_by text,
  changed_by_name text,
  changes jsonb not null default '{}'::jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists project_billing_audit_project_idx
  on public.project_billing_audit_log (project_id, changed_at desc);

alter table public.project_billing_records enable row level security;
alter table public.project_billing_audit_log enable row level security;

drop policy if exists "project_billing_records_select" on public.project_billing_records;
create policy "project_billing_records_select" on public.project_billing_records
  for select to anon, authenticated using (true);

drop policy if exists "project_billing_records_insert" on public.project_billing_records;
create policy "project_billing_records_insert" on public.project_billing_records
  for insert to anon, authenticated with check (true);

drop policy if exists "project_billing_records_update" on public.project_billing_records;
create policy "project_billing_records_update" on public.project_billing_records
  for update to anon, authenticated using (true) with check (true);

drop policy if exists "project_billing_audit_select" on public.project_billing_audit_log;
create policy "project_billing_audit_select" on public.project_billing_audit_log
  for select to anon, authenticated using (true);

drop policy if exists "project_billing_audit_insert" on public.project_billing_audit_log;
create policy "project_billing_audit_insert" on public.project_billing_audit_log
  for insert to anon, authenticated with check (true);

grant select, insert, update on public.project_billing_records to anon, authenticated;
grant select, insert on public.project_billing_audit_log to anon, authenticated;
grant usage, select on sequence public.project_billing_audit_log_id_seq to anon, authenticated;

notify pgrst, 'reload schema';
